#غيرنا بي شي
services:
  db:
    image: postgres:17
    container_name: postgres_dev

    environment:
      POSTGRES_DB: makok
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      Database: '{"default":{"HOST":"db"}}'
      Local_Settings_Path: "/local/settings.prod.py"

  frontend-proxy:
    image: nginx:latest
    container_name: frontend_proxy
    ports:
      - "8001:8001"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  postgres_data:
    driver: local
