services:
  db:
    image: postgres:17
    container_name: postgres_dev

    environment:
      POSTGRES_DB: makok
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
    CORESETTINGS_LOCAL_SETTINGS_PATH: "local/settings.prod.py"
    CORESETTINGS_IN_DOCKER: "True"

    volumes:
      - static_volume:/opt/makok/staticfiles

  frontend-proxy:
    image: nginx:latest
    container_name: frontend_proxy

    ports:
      - "8001:8001"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/staticfiles:ro

    depends_on:
      - app

volumes:
  postgres_data:
    driver: local

  static_volume:
    driver: local

  media_volume:
    driver: local
