# Generated by Django 6.0.1 on 2026-03-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customers_orders_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
