# Generated by Django 6.0.1 on 2026-03-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orderitem_position_orderitem_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
