# Generated by Django 6.0.1 on 2026-03-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderitem_color_image_orderitem_design_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='design_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='logo_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
